export enum AdminDataTypeEnum {
    NONE,
    CHANNEL_CREATED,
    CHANNEL_UPDATED,
    CHANNEL_DELETED,
    USER_CREATED,
    USER_UPDATED,
    USER_DETELED,
    CHANNEL_USER_CREATED,
    CHANNEL_USER_UPDATED,
    CHANNEL_USER_DELETED,
}
